name: Tests

on:
    pull_request:
        branches:
          - develop
          - main
        
jobs:
    run-tests:
        runs-on: ubuntu-latest
        steps:
          - name: Repo Checkout
            uses: actions/checkout@v3
            
          - name: Python Setup
            uses: actions/setup-python@v4
            with:
                python-version: "3.10"
                
          - name: Poetry Install
            uses: snok/install-poetry@v1
            
          - name: Dependency Install
            run: |
                poetry install --with test --no-interaction
                
          - name: Run Tests
            run: |
                poetry run \
                pytest \
                    --junitxml=pytest.xml \
                    --cov-report=term-missing:skip-covered \
                    --cov=./src \
                | tee pytest-coverage.txt
                
          - name: Test PR Comment
            uses: MishaKav/pytest-coverage-comment@main
            with:
                pytest-coverage-path: ./pytest-coverage.txt
                junitxml-path: ./pytest.xml
